services:
  db:
    build:
      context: ./server/PostgreSQL/db
      dockerfile: Dockerfile
    container_name: meteor_postgresdb
    env_file:
      - .env
    networks:
      - int
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meteor_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - int
      - ext

networks:
  int:
    driver: bridge
    internal: true
  ext:
    driver: bridge
