name: Meteor CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: .\Scrum\software\
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.21.3'
          
      - name: Instalar Meteor
        run: |
          curl https://install.meteor.com/ | sh
          
      - name: Verificar directorio
        run: |
          pwd
          ls -la
          
      - name: Instalar dependencias
        run: meteor npm install
        
      - name: Ejecutar pruebas
        run: meteor npm test